version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: carlosharo/keta-app:latest
    env_file:
      - .env
    volumes:
      - ./keta:/var/www/html
    ports:
      - '8000:8000'
    command: >
      sh -c "chmod +x start-app.sh && ./start-app.sh"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
        POSTGRES_PASSWORD: ${PASSWORD_DB}
        POSTGRES_USER: ${USER}
        POSTGRES_DB: ${NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '${PORT}:5432' #Localport:Dockerport
    container_name: postgres_db_keta

volumes:
  postgres-data:

