version: "3"

services:
  app:  # Service name
    build: .  # Build the Docker image using the Dockerfile in the current directory
    container_name: keta_backend  # Specify the container name as "keta"
    env_file:
      - .env  # Load environment variables from the .env file
    volumes:
      - ./keta:/var/www/html  # Mount the ./keta directory in your project to /var/www/html in the container
    ports:
      - '8005:80'  # Map host port 8005 to container port 80