version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: carlosharo/keta-app:latest
    env_file:
      - .env
    volumes:
      - ./keta:/var/www/html
    ports:
      - '8005:80'
