# Generated by Django 4.2.3 on 2023-08-03 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jusuarios',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('direccionmac', models.CharField(blank=True, max_length=100, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('ipcreacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ipmodificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=True, null=True)),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=100)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'jusuarios',
            },
        ),
        migrations.CreateModel(
            name='Jcanalesrecepciones',
            fields=[
                ('idcanalrecepcion', models.AutoField(primary_key=True, serialize=False)),
                ('codigocanalrecepcion', models.CharField(blank=True, max_length=2, null=True)),
                ('descripcioncanalrecepcion', models.CharField(max_length=250)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jcanalesrecepciones',
            },
        ),
        migrations.CreateModel(
            name='Jcargos',
            fields=[
                ('idcargo', models.AutoField(primary_key=True, serialize=False)),
                ('codigocargo', models.CharField(blank=True, max_length=10, null=True)),
                ('descripcioncargo', models.CharField(blank=True, max_length=200, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jcargos',
            },
        ),
        migrations.CreateModel(
            name='Jclasestarjetas',
            fields=[
                ('idclasetarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('codigoclasetarjeta', models.CharField(blank=True, max_length=2, null=True)),
                ('descripcionclasetarjeta', models.CharField(blank=True, max_length=100, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jclasestarjetas',
            },
        ),
        migrations.CreateModel(
            name='Jclasificacionesresoluciones',
            fields=[
                ('idclasificacionresolucion', models.AutoField(primary_key=True, serialize=False)),
                ('codigoclasificacionresolucion', models.CharField(blank=True, max_length=4, null=True)),
                ('descripcionclasificacion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jclasificacionesresoluciones',
            },
        ),
        migrations.CreateModel(
            name='Jconceptos',
            fields=[
                ('idconcepto', models.AutoField(primary_key=True, serialize=False)),
                ('codigoconcepto', models.CharField(blank=True, max_length=4, null=True)),
                ('descripcionconcepto', models.TextField(blank=True, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jconceptos',
            },
        ),
        migrations.CreateModel(
            name='Jcorporaciones',
            fields=[
                ('idcorporacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecorporacion', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcioncorporacion', models.CharField(blank=True, max_length=500, null=True)),
                ('representantelegal', models.CharField(blank=True, max_length=200, null=True)),
                ('ruc', models.CharField(blank=True, null=True)),
                ('direccioncorporacion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefonocorporacion', models.CharField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('ipcreacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ipmodificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jcorporaciones',
            },
        ),
        migrations.CreateModel(
            name='Jestados',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('codigoestado', models.BigIntegerField(blank=True, null=True)),
                ('descripcionestado', models.CharField(blank=True, max_length=250, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jestados',
            },
        ),
        migrations.CreateModel(
            name='Jgeneros',
            fields=[
                ('idgenero', models.AutoField(primary_key=True, serialize=False)),
                ('codigogenero', models.CharField(blank=True, max_length=2, null=True)),
                ('descripciongenero', models.CharField(blank=True, max_length=50, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jgeneros',
            },
        ),
        migrations.CreateModel(
            name='Jgeografia',
            fields=[
                ('idgeografia', models.AutoField(primary_key=True, serialize=False)),
                ('codigogeografia', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel', models.BigIntegerField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('ipcreacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ipmodificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('fkidgeografia', models.ForeignKey(blank=True, db_column='fkidgeografia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jgeografia')),
            ],
            options={
                'db_table': 'jgeografia',
            },
        ),
        migrations.CreateModel(
            name='Jmarcastarjetas',
            fields=[
                ('idmarcatarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('codigomarcatarjeta', models.CharField(blank=True, max_length=2, null=True)),
                ('descripcionmarcatarjeta', models.CharField(blank=True, max_length=100, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jmarcastarjetas',
            },
        ),
        migrations.CreateModel(
            name='Jpersonas',
            fields=[
                ('idpersona', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(blank=True, max_length=10, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('apellido', models.CharField(blank=True, max_length=250, null=True)),
                ('emailcliente', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('direccion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('idgenero', models.ForeignKey(blank=True, db_column='idgenero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jgeneros')),
            ],
            options={
                'db_table': 'jpersonas',
            },
        ),
        migrations.CreateModel(
            name='Jprioridades',
            fields=[
                ('idprioridad', models.AutoField(primary_key=True, serialize=False)),
                ('codigoprioridad', models.CharField(blank=True, max_length=2, null=True)),
                ('descripcionprioridad', models.CharField(blank=True, max_length=50, null=True)),
                ('duracionprioridad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jprioridades',
            },
        ),
        migrations.CreateModel(
            name='Jproblemas',
            fields=[
                ('idproblema', models.AutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('numeroticket', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcionasunto', models.TextField(blank=True, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('archivo', models.CharField(blank=True, max_length=500, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('idcanalrecepcion', models.ForeignKey(blank=True, db_column='idcanalrecepcion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jcanalesrecepciones')),
                ('idconcepto', models.ForeignKey(blank=True, db_column='idconcepto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jconceptos')),
                ('idpersona', models.ForeignKey(blank=True, db_column='idpersona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jpersonas')),
                ('idprioridad', models.ForeignKey(blank=True, db_column='idprioridad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jprioridades')),
            ],
            options={
                'db_table': 'jproblemas',
            },
        ),
        migrations.CreateModel(
            name='Jresoluciones',
            fields=[
                ('idresolucion', models.AutoField(primary_key=True, serialize=False)),
                ('numeroresolucion', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcionresolucion', models.TextField(blank=True, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('idclasificacionresolucion', models.ForeignKey(blank=True, db_column='idclasificacionresolucion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jclasificacionesresoluciones')),
            ],
            options={
                'db_table': 'jresoluciones',
            },
        ),
        migrations.CreateModel(
            name='Jroles',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcionrol', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('ipcreacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ipmodificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jroles',
            },
        ),
        migrations.CreateModel(
            name='Jtickettipos',
            fields=[
                ('idtipoticket', models.AutoField(primary_key=True, serialize=False)),
                ('descripciontipoticket', models.CharField(blank=True, max_length=250, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jtickettipos',
            },
        ),
        migrations.CreateModel(
            name='Jtiporesoluciones',
            fields=[
                ('idtiporesolucion', models.AutoField(primary_key=True, serialize=False)),
                ('codigotiporesoulcion', models.CharField(blank=True, max_length=4, null=True)),
                ('descripciontiporesolucion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jtiporesoluciones',
            },
        ),
        migrations.CreateModel(
            name='Jtiposcomentarios',
            fields=[
                ('idtipocomentario', models.AutoField(primary_key=True, serialize=False)),
                ('codigotipocomentario', models.CharField(blank=True, max_length=3, null=True)),
                ('descripciontipocomentario', models.CharField(blank=True, max_length=250, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jtiposcomentarios',
            },
        ),
        migrations.CreateModel(
            name='Jtiposidentificaciones',
            fields=[
                ('idtipoidentificacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigotipoidentificacion', models.CharField(blank=True, max_length=2, null=True)),
                ('descripciontipoidentificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jtiposidentificaciones',
            },
        ),
        migrations.CreateModel(
            name='Jtipospersonas',
            fields=[
                ('idtipopersona', models.AutoField(primary_key=True, serialize=False)),
                ('codigotipopersona', models.CharField(blank=True, null=True)),
                ('descripciontipopersona', models.CharField(blank=True, max_length=50, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jtipospersonas',
            },
        ),
        migrations.CreateModel(
            name='Jtiposproductos',
            fields=[
                ('idtipoproducto', models.AutoField(primary_key=True, serialize=False)),
                ('codigotipoproducto', models.CharField(blank=True, max_length=4, null=True)),
                ('descripciontipoproducto', models.CharField(blank=True, max_length=250, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jtiposproductos',
            },
        ),
        migrations.CreateModel(
            name='Jtipostarjetas',
            fields=[
                ('idtipotarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('codigotipotarjeta', models.CharField(blank=True, max_length=4, null=True)),
                ('descripciontipotarjeta', models.CharField(blank=True, max_length=100, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jtipostarjetas',
            },
        ),
        migrations.CreateModel(
            name='Jtipostransacciones',
            fields=[
                ('idtipotransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('codigotipotransaccion', models.CharField(blank=True, max_length=4, null=True)),
                ('descripciontipotransaccion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jtipostransacciones',
            },
        ),
        migrations.CreateModel(
            name='Jvaloresresoluciones',
            fields=[
                ('idvaloresresoluciones', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('interesmonto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('totalmonto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observacionmonto', models.CharField(blank=True, max_length=500, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('idresolucion', models.ForeignKey(blank=True, db_column='idresolucion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jresoluciones')),
            ],
            options={
                'db_table': 'jvaloresresoluciones',
            },
        ),
        migrations.CreateModel(
            name='Jtarjetas',
            fields=[
                ('idtarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('idclasetarjeta', models.ForeignKey(blank=True, db_column='idclasetarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jclasestarjetas')),
                ('idmarcatarjeta', models.ForeignKey(blank=True, db_column='idmarcatarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jmarcastarjetas')),
                ('idtipotarjeta', models.ForeignKey(blank=True, db_column='idtipotarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtipostarjetas')),
            ],
            options={
                'db_table': 'jtarjetas',
            },
        ),
        migrations.CreateModel(
            name='Jtareasticket',
            fields=[
                ('idtarea', models.AutoField(primary_key=True, serialize=False)),
                ('descripciontarea', models.CharField(blank=True, max_length=500, null=True)),
                ('indicador', models.CharField(blank=True, max_length=2, null=True)),
                ('fechaasignacion', models.DateTimeField(blank=True, null=True)),
                ('fechaentrega', models.DateTimeField(blank=True, null=True)),
                ('archivo', models.CharField(blank=True, max_length=500, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('fkidtarea', models.ForeignKey(blank=True, db_column='fkidtarea', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtareasticket')),
                ('idestado', models.ForeignKey(blank=True, db_column='idestado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jestados')),
                ('idprioridad', models.ForeignKey(blank=True, db_column='idprioridad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jprioridades')),
                ('idproblema', models.ForeignKey(blank=True, db_column='idproblema', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jproblemas')),
                ('idusuarioasignado', models.ForeignKey(blank=True, db_column='idusuarioasignado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jtareasticket_idusuarioasignado_set', to=settings.AUTH_USER_MODEL)),
                ('idusuarioqasigno', models.ForeignKey(blank=True, db_column='idusuarioqasigno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tareaprincipal', models.ForeignKey(blank=True, db_column='tareaprincipal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jtareasticket_tareaprincipal_set', to='users.jtareasticket')),
            ],
            options={
                'db_table': 'jtareasticket',
            },
        ),
        migrations.CreateModel(
            name='Jsucursales',
            fields=[
                ('idsucursal', models.AutoField(primary_key=True, serialize=False)),
                ('codigosucursal', models.CharField(blank=True, max_length=2, null=True)),
                ('nombresucursal', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcionsucursal', models.CharField(blank=True, max_length=500, null=True)),
                ('direccionsucursal', models.CharField(blank=True, max_length=200, null=True)),
                ('telefonosucursal', models.CharField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('ipcreacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ipmodificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('idcorporacion', models.ForeignKey(blank=True, db_column='idcorporacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jcorporaciones')),
                ('idpais', models.ForeignKey(blank=True, db_column='idpais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jgeografia')),
            ],
            options={
                'db_table': 'jsucursales',
            },
        ),
        migrations.CreateModel(
            name='Jseguimientostareas',
            fields=[
                ('idseguimientotarea', models.AutoField(primary_key=True, serialize=False)),
                ('detalleresolucion', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('archivo', models.CharField(blank=True, max_length=500, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('idtarea', models.ForeignKey(blank=True, db_column='idtarea', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtareasticket')),
            ],
            options={
                'db_table': 'jseguimientostareas',
            },
        ),
        migrations.AddField(
            model_name='jresoluciones',
            name='idtarea',
            field=models.ForeignKey(blank=True, db_column='idtarea', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtareasticket'),
        ),
        migrations.AddField(
            model_name='jresoluciones',
            name='idtiporesolucion',
            field=models.ForeignKey(blank=True, db_column='idtiporesolucion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtiporesoluciones'),
        ),
        migrations.AddField(
            model_name='jproblemas',
            name='idsucursal',
            field=models.ForeignKey(blank=True, db_column='idsucursal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jsucursales'),
        ),
        migrations.AddField(
            model_name='jproblemas',
            name='idtarjeta',
            field=models.ForeignKey(blank=True, db_column='idtarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtarjetas'),
        ),
        migrations.AddField(
            model_name='jproblemas',
            name='idtipocomentario',
            field=models.ForeignKey(blank=True, db_column='idtipocomentario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtiposcomentarios'),
        ),
        migrations.AddField(
            model_name='jproblemas',
            name='idtipoticket',
            field=models.ForeignKey(blank=True, db_column='idtipoticket', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtickettipos'),
        ),
        migrations.AddField(
            model_name='jproblemas',
            name='idtipotransaccion',
            field=models.ForeignKey(blank=True, db_column='idtipotransaccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtipostransacciones'),
        ),
        migrations.AddField(
            model_name='jproblemas',
            name='idusuario',
            field=models.ForeignKey(blank=True, db_column='idusuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jpersonas',
            name='idtipoidentificacion',
            field=models.ForeignKey(blank=True, db_column='idtipoidentificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtiposidentificaciones'),
        ),
        migrations.AddField(
            model_name='jpersonas',
            name='idtipopersona',
            field=models.ForeignKey(blank=True, db_column='idtipopersona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtipospersonas'),
        ),
        migrations.CreateModel(
            name='Jestadotareas',
            fields=[
                ('idestadotarea', models.AutoField(primary_key=True, serialize=False)),
                ('diaoptimo', models.BigIntegerField(blank=True, null=True)),
                ('diarequerido', models.BigIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('idtarea', models.ForeignKey(blank=True, db_column='idtarea', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtareasticket')),
            ],
            options={
                'db_table': 'jestadotareas',
            },
        ),
        migrations.CreateModel(
            name='Jdepartamentos',
            fields=[
                ('iddepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('codigodepartamento', models.CharField(blank=True, max_length=2, null=True)),
                ('nombredepartamento', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('descripciondepartamento', models.CharField(blank=True, max_length=500, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('ipcreacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ipmodificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecharegistro', models.DateTimeField(blank=True, null=True)),
                ('idsucursal', models.ForeignKey(blank=True, db_column='idsucursal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jsucursales')),
            ],
            options={
                'db_table': 'jdepartamentos',
            },
        ),
        migrations.AddField(
            model_name='jcorporaciones',
            name='idpais',
            field=models.ForeignKey(blank=True, db_column='idpais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jgeografia'),
        ),
        migrations.AddField(
            model_name='jconceptos',
            name='idtipoproducto',
            field=models.ForeignKey(blank=True, db_column='idtipoproducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtiposproductos'),
        ),
        migrations.AddField(
            model_name='jusuarios',
            name='idcargo',
            field=models.ForeignKey(blank=True, db_column='idcargo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jcargos'),
        ),
        migrations.AddField(
            model_name='jusuarios',
            name='iddepartamento',
            field=models.ForeignKey(blank=True, db_column='iddepartamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jdepartamentos'),
        ),
        migrations.AddField(
            model_name='jusuarios',
            name='idpersona',
            field=models.ForeignKey(blank=True, db_column='idpersona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jpersonas'),
        ),
        migrations.AddField(
            model_name='jusuarios',
            name='idrol',
            field=models.ForeignKey(blank=True, db_column='idrol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jroles'),
        ),
        migrations.AddField(
            model_name='jusuarios',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
