# Generated by Django 4.2.3 on 2023-07-28 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jusuarios',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('direccionmac', models.CharField(blank=True, max_length=100, null=True)),
                ('date_joined', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('ipcreacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ipmodificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=True, null=True)),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'jusuarios',
            },
        ),
        migrations.CreateModel(
            name='Jcanalesrecepciones',
            fields=[
                ('idcanalrecepcion', models.AutoField(primary_key=True, serialize=False)),
                ('codigocanalrecepcion', models.CharField(blank=True, max_length=2, null=True)),
                ('etiquetacanalrecepcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'jcanalesrecepciones',
            },
        ),
        migrations.CreateModel(
            name='Jcargos',
            fields=[
                ('idcargo', models.AutoField(primary_key=True, serialize=False)),
                ('codigocargo', models.CharField(blank=True, max_length=10, null=True)),
                ('etiquetacargo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'jcargos',
            },
        ),
        migrations.CreateModel(
            name='Jclasestarjetas',
            fields=[
                ('idclasetarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('codigoclasetarjeta', models.CharField(blank=True, max_length=2, null=True)),
                ('nombreclasetarjeta', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'jclasestarjetas',
            },
        ),
        migrations.CreateModel(
            name='Jclasificacionresoluciones',
            fields=[
                ('idclasificacionresolucion', models.AutoField(primary_key=True, serialize=False)),
                ('codigoclasificacionresolucion', models.CharField(blank=True, max_length=4, null=True)),
                ('etiquetaclasificacion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'jclasificacionresoluciones',
            },
        ),
        migrations.CreateModel(
            name='Jconceptos',
            fields=[
                ('idconcepto', models.AutoField(primary_key=True, serialize=False)),
                ('codigoconcepto', models.CharField(blank=True, max_length=4, null=True)),
                ('etiquetaconcepto', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jconceptos',
            },
        ),
        migrations.CreateModel(
            name='Jcorporaciones',
            fields=[
                ('idcorporacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecorporacion', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcioncorporacion', models.CharField(blank=True, max_length=500, null=True)),
                ('representantelegal', models.CharField(blank=True, max_length=200, null=True)),
                ('ruc', models.CharField(blank=True, null=True)),
                ('direccioncorporacion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefonocorporacion', models.CharField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('ipcreacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ipmodificacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'jcorporaciones',
            },
        ),
        migrations.CreateModel(
            name='Jestados',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('codigoestado', models.BigIntegerField(blank=True, null=True)),
                ('etiquetaestado', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'jestados',
            },
        ),
        migrations.CreateModel(
            name='Jgeneros',
            fields=[
                ('idgenero', models.AutoField(primary_key=True, serialize=False)),
                ('codigogenero', models.CharField(blank=True, max_length=2, null=True)),
                ('etiquetagenero', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'jgeneros',
            },
        ),
        migrations.CreateModel(
            name='Jgeografia',
            fields=[
                ('idgeografia', models.AutoField(primary_key=True, serialize=False)),
                ('codigogeografia', models.CharField(blank=True, max_length=2, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel', models.BigIntegerField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('ipcreacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ipmodificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fkidgeografia', models.ForeignKey(blank=True, db_column='fkidgeografia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jgeografia')),
            ],
            options={
                'db_table': 'jgeografia',
            },
        ),
        migrations.CreateModel(
            name='Jmarcastarjetas',
            fields=[
                ('idmarcatarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('codigomarcatarjeta', models.CharField(blank=True, max_length=2, null=True)),
                ('nombremarcatarjeta', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'jmarcastarjetas',
            },
        ),
        migrations.CreateModel(
            name='Jpersonas',
            fields=[
                ('idpersona', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('apellido', models.CharField(blank=True, max_length=250, null=True)),
                ('emailcliente', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('direccion', models.CharField(blank=True, max_length=500, null=True)),
                ('idgenero', models.ForeignKey(blank=True, db_column='idgenero', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jgeneros')),
            ],
            options={
                'db_table': 'jpersonas',
            },
        ),
        migrations.CreateModel(
            name='Jprioridades',
            fields=[
                ('idprioridad', models.AutoField(primary_key=True, serialize=False)),
                ('codigoprioridad', models.CharField(blank=True, max_length=2, null=True)),
                ('etiquetaprioridad', models.CharField(blank=True, max_length=50, null=True)),
                ('duracionprioridad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'jprioridades',
            },
        ),
        migrations.CreateModel(
            name='Jproblemas',
            fields=[
                ('idproblema', models.AutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('numerotike', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcionasunto', models.TextField(blank=True, null=True)),
                ('archivo', models.CharField(blank=True, max_length=500, null=True)),
                ('idcanalrecepcion', models.ForeignKey(blank=True, db_column='idcanalrecepcion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jcanalesrecepciones')),
                ('idconcepto', models.ForeignKey(blank=True, db_column='idconcepto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jconceptos')),
                ('idpersona', models.ForeignKey(blank=True, db_column='idpersona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jpersonas')),
                ('idprioridad', models.ForeignKey(blank=True, db_column='idprioridad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jprioridades')),
            ],
            options={
                'db_table': 'jproblemas',
            },
        ),
        migrations.CreateModel(
            name='Jproblemastickets',
            fields=[
                ('idproblematicket', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('interesmonto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('totalmonto', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observacionmontores', models.CharField(blank=True, max_length=500, null=True)),
                ('montoreclamo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observacionmontorec', models.CharField(blank=True, max_length=500, null=True)),
                ('idproblema', models.ForeignKey(blank=True, db_column='idproblema', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jproblemas')),
            ],
            options={
                'db_table': 'jproblemastickets',
            },
        ),
        migrations.CreateModel(
            name='Jroles',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcionrol', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('ipcreacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ipmodificacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'jroles',
            },
        ),
        migrations.CreateModel(
            name='Jtickettipos',
            fields=[
                ('idticketipo', models.AutoField(primary_key=True, serialize=False)),
                ('etiquetatickettipo', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'jtickettipos',
            },
        ),
        migrations.CreateModel(
            name='Jtipocomentarios',
            fields=[
                ('idtipocomentario', models.AutoField(primary_key=True, serialize=False)),
                ('codigotipocomentario', models.CharField(blank=True, max_length=3, null=True)),
                ('etiquetatipocomentario', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'jtipocomentarios',
            },
        ),
        migrations.CreateModel(
            name='Jtipoidentificaciones',
            fields=[
                ('idtipoidentificacion', models.AutoField(primary_key=True, serialize=False)),
                ('codigotipoidentificacion', models.CharField(blank=True, max_length=2, null=True)),
                ('nombretipoidentificacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'jtipoidentificaciones',
            },
        ),
        migrations.CreateModel(
            name='Jtipopersonas',
            fields=[
                ('idtipopersona', models.AutoField(primary_key=True, serialize=False)),
                ('codigotipopersona', models.CharField(blank=True, null=True)),
                ('etiquetatipopersona', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'jtipopersonas',
            },
        ),
        migrations.CreateModel(
            name='Jtipoproductos',
            fields=[
                ('idtipoproducto', models.AutoField(primary_key=True, serialize=False)),
                ('codigotipoproducto', models.CharField(blank=True, max_length=4, null=True)),
                ('nombretipoproducto', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'jtipoproductos',
            },
        ),
        migrations.CreateModel(
            name='Jtiporesoluciones',
            fields=[
                ('idtiporesolucion', models.AutoField(primary_key=True, serialize=False)),
                ('codigotiporesoulcion', models.CharField(blank=True, max_length=4, null=True)),
                ('etiquetatiporesoulucion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'jtiporesoluciones',
            },
        ),
        migrations.CreateModel(
            name='Jtipotarjetas',
            fields=[
                ('idtipotarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('codigotipotarjeta', models.CharField(blank=True, max_length=4, null=True)),
                ('nombretipotarjeta', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'jtipotarjetas',
            },
        ),
        migrations.CreateModel(
            name='Jtipotransacciones',
            fields=[
                ('idtipotransaccion', models.AutoField(primary_key=True, serialize=False)),
                ('codigotipotransaccion', models.CharField(blank=True, max_length=4, null=True)),
                ('etiquetatipotransaccion', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'jtipotransacciones',
            },
        ),
        migrations.CreateModel(
            name='Jtickettareas',
            fields=[
                ('idticket', models.AutoField(primary_key=True, serialize=False)),
                ('descripciontarea', models.CharField(blank=True, max_length=500, null=True)),
                ('indicador', models.CharField(blank=True, max_length=2, null=True)),
                ('fechaasignacion', models.DateTimeField(blank=True, null=True)),
                ('fechaentrega', models.DateTimeField(blank=True, null=True)),
                ('archivo', models.CharField(blank=True, max_length=500, null=True)),
                ('fkidticket', models.ForeignKey(blank=True, db_column='fkidticket', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtickettareas')),
                ('idestado', models.ForeignKey(blank=True, db_column='idestado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jestados')),
                ('idprioridad', models.ForeignKey(blank=True, db_column='idprioridad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jprioridades')),
                ('idproblematicket', models.ForeignKey(blank=True, db_column='idproblematicket', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jproblemastickets')),
                ('idusuarioasignado', models.ForeignKey(blank=True, db_column='idusuarioasignado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('idusuarioqasigno', models.ForeignKey(blank=True, db_column='idusuarioqasigno', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jtickettareas_idusuarioqasigno_set', to=settings.AUTH_USER_MODEL)),
                ('ticketprincipal', models.ForeignKey(blank=True, db_column='ticketprincipal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jtickettareas_ticketprincipal_set', to='users.jtickettareas')),
            ],
            options={
                'db_table': 'jtickettareas',
            },
        ),
        migrations.CreateModel(
            name='Jtarjetas',
            fields=[
                ('idtarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('idclasetarjeta', models.ForeignKey(blank=True, db_column='idclasetarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jclasestarjetas')),
                ('idmarcatarjeta', models.ForeignKey(blank=True, db_column='idmarcatarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jmarcastarjetas')),
                ('idtipotarjeta', models.ForeignKey(blank=True, db_column='idtipotarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtipotarjetas')),
            ],
            options={
                'db_table': 'jtarjetas',
            },
        ),
        migrations.CreateModel(
            name='Jsucursales',
            fields=[
                ('idsucursal', models.AutoField(primary_key=True, serialize=False)),
                ('codigosucursal', models.CharField(blank=True, max_length=2, null=True)),
                ('nombresucursal', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcionsucursal', models.CharField(blank=True, max_length=500, null=True)),
                ('direccionsucursal', models.CharField(blank=True, max_length=200, null=True)),
                ('telefonosucursal', models.CharField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('ipcreacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ipmodificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('idcorporacion', models.ForeignKey(blank=True, db_column='idcorporacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jcorporaciones')),
                ('idpais', models.ForeignKey(blank=True, db_column='idpais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jgeografia')),
            ],
            options={
                'db_table': 'jsucursales',
            },
        ),
        migrations.CreateModel(
            name='Jresoluciones',
            fields=[
                ('idresolucion', models.AutoField(primary_key=True, serialize=False)),
                ('detalleresolucion', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('idclasificacionresolucion', models.ForeignKey(blank=True, db_column='idclasificacionresolucion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jclasificacionresoluciones')),
                ('idticket', models.ForeignKey(blank=True, db_column='idticket', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtickettareas')),
                ('idtiporesolucion', models.ForeignKey(blank=True, db_column='idtiporesolucion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtiporesoluciones')),
            ],
            options={
                'db_table': 'jresoluciones',
            },
        ),
        migrations.AddField(
            model_name='jproblemas',
            name='idsucursal',
            field=models.ForeignKey(blank=True, db_column='idsucursal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jsucursales'),
        ),
        migrations.AddField(
            model_name='jproblemas',
            name='idtarjeta',
            field=models.ForeignKey(blank=True, db_column='idtarjeta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtarjetas'),
        ),
        migrations.AddField(
            model_name='jproblemas',
            name='idticketipo',
            field=models.ForeignKey(blank=True, db_column='idticketipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtickettipos'),
        ),
        migrations.AddField(
            model_name='jproblemas',
            name='idtipocomentario',
            field=models.ForeignKey(blank=True, db_column='idtipocomentario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtipocomentarios'),
        ),
        migrations.AddField(
            model_name='jproblemas',
            name='idtipotransaccion',
            field=models.ForeignKey(blank=True, db_column='idtipotransaccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtipotransacciones'),
        ),
        migrations.AddField(
            model_name='jpersonas',
            name='idtipoidentificacion',
            field=models.ForeignKey(blank=True, db_column='idtipoidentificacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtipoidentificaciones'),
        ),
        migrations.AddField(
            model_name='jpersonas',
            name='idtipopersona',
            field=models.ForeignKey(blank=True, db_column='idtipopersona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtipopersonas'),
        ),
        migrations.CreateModel(
            name='Jestadotareas',
            fields=[
                ('idestadotarea', models.AutoField(primary_key=True, serialize=False)),
                ('diaoptimo', models.BigIntegerField(blank=True, null=True)),
                ('diarequerido', models.BigIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('idticket', models.ForeignKey(blank=True, db_column='idticket', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtickettareas')),
            ],
            options={
                'db_table': 'jestadotareas',
            },
        ),
        migrations.CreateModel(
            name='Jdepartamentos',
            fields=[
                ('iddepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('codigodepartamento', models.CharField(blank=True, max_length=2, null=True)),
                ('nombredepartamento', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('descripciondepartamento', models.CharField(blank=True, max_length=500, null=True)),
                ('fechacreacion', models.DateTimeField(blank=True, null=True)),
                ('fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('ipcreacion', models.CharField(blank=True, max_length=50, null=True)),
                ('ipmodificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('idsucursal', models.ForeignKey(blank=True, db_column='idsucursal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jsucursales')),
            ],
            options={
                'db_table': 'jdepartamentos',
            },
        ),
        migrations.AddField(
            model_name='jcorporaciones',
            name='idpais',
            field=models.ForeignKey(blank=True, db_column='idpais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jgeografia'),
        ),
        migrations.AddField(
            model_name='jconceptos',
            name='idtipoproducto',
            field=models.ForeignKey(blank=True, db_column='idtipoproducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jtipoproductos'),
        ),
        migrations.AddField(
            model_name='jusuarios',
            name='idcargo',
            field=models.ForeignKey(blank=True, db_column='idcargo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jcargos'),
        ),
        migrations.AddField(
            model_name='jusuarios',
            name='iddepartamento',
            field=models.ForeignKey(blank=True, db_column='iddepartamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jdepartamentos'),
        ),
        migrations.AddField(
            model_name='jusuarios',
            name='idpersona',
            field=models.ForeignKey(blank=True, db_column='idpersona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jpersonas'),
        ),
        migrations.AddField(
            model_name='jusuarios',
            name='idrol',
            field=models.ForeignKey(blank=True, db_column='idrol', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.jroles'),
        ),
        migrations.AddField(
            model_name='jusuarios',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
